language: python
python:
  - 2.6
  - 2.7
  - 3.3
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install pytest pytest-cov coveralls
  - python setup.py develop
# command to run tests, e.g. python setup.py test
script: py.test --cov capacity
after_success:
  coveralls
